export const MASTER_NUMBERS = new Set([11, 22, 33])

// Pythagorean letter-to-number chart
export const LETTER_VALUES: Record<string, number> = {
  A: 1, J: 1, S: 1,
  B: 2, K: 2, T: 2,
  C: 3, L: 3, U: 3,
  D: 4, M: 4, V: 4,
  E: 5, N: 5, W: 5,
  F: 6, O: 6, X: 6,
  G: 7, P: 7, Y: 7,
  H: 8, Q: 8, Z: 8,
  I: 9, R: 9,
}

export const VOWELS = new Set(['A', 'E', 'I', 'O', 'U', 'Y'])

export interface NumberMeaning {
  number: number
  nameVi: string
  keywords: string[]
  general: string
  asLifePath: string
  asExpression: string
  asSoulUrge: string
  asPersonality: string
  asBirthday: string
  asMaturity: string
  asChallenge: string
  asPinnacle: string
  asPersonalYear: string
}

export const NUMBER_MEANINGS: Record<number, NumberMeaning> = {
  0: {
    number: 0,
    nameVi: 'Thử Thách Tự Do',
    keywords: ['tự do', 'lựa chọn', 'tiềm năng'],
    general: 'Số 0 đại diện cho sự tự do tuyệt đối trong lựa chọn. Bạn có thể đối mặt với mọi thử thách và biến chúng thành cơ hội phát triển.',
    asLifePath: '',
    asExpression: '',
    asSoulUrge: '',
    asPersonality: '',
    asBirthday: '',
    asMaturity: '',
    asChallenge: 'Thử thách số 0 cho thấy bạn có thể phải đối mặt với tất cả các thử thách cùng lúc. Bạn có tiềm năng vượt qua mọi trở ngại nhưng cần kỷ luật tự thân để không bị phân tán.',
    asPinnacle: '',
    asPersonalYear: '',
  },
  1: {
    number: 1,
    nameVi: 'Số Lãnh Đạo',
    keywords: ['lãnh đạo', 'độc lập', 'sáng tạo', 'tiên phong'],
    general: 'Số 1 tượng trưng cho sự khởi đầu, lãnh đạo và tính độc lập. Bạn có khả năng tiên phong, tự tin và quyết đoán trong mọi việc.',
    asLifePath: 'Con đường đời số 1 dẫn bạn đến vai trò lãnh đạo. Bạn sinh ra để đi đầu, khai phá những con đường mới và truyền cảm hứng cho người khác bằng sự dũng cảm và quyết tâm.',
    asExpression: 'Bạn thể hiện bản thân qua sự độc lập và sáng tạo. Tài năng tự nhiên của bạn nằm ở khả năng dẫn dắt, khởi xướng ý tưởng mới và hành động quyết đoán.',
    asSoulUrge: 'Tâm hồn bạn khao khát sự độc lập và tự do. Bạn muốn được là chính mình, tự quyết định con đường riêng và đạt thành tựu bằng nỗ lực bản thân.',
    asPersonality: 'Bạn tạo ấn tượng đầu tiên mạnh mẽ, tự tin và có vẻ ngoài của người lãnh đạo bẩm sinh. Người khác nhìn bạn như một người quyết đoán và đáng tin cậy.',
    asBirthday: 'Sinh ngày mang năng lượng số 1 cho thấy bạn có tư chất lãnh đạo bẩm sinh, ý chí mạnh mẽ và khả năng tự lập cao.',
    asMaturity: 'Khi trưởng thành, bạn sẽ ngày càng phát triển khả năng lãnh đạo và tính độc lập. Nửa sau cuộc đời là thời điểm bạn tỏa sáng với vai trò tiên phong.',
    asChallenge: 'Thử thách số 1 yêu cầu bạn vượt qua sự thiếu tự tin hoặc ngược lại, tính ích kỷ và độc đoán. Bạn cần học cách cân bằng giữa độc lập và hợp tác.',
    asPinnacle: 'Đỉnh cao số 1 mang đến cơ hội phát triển cá nhân, khởi nghiệp và khẳng định vị trí lãnh đạo. Đây là thời kỳ bạn cần dũng cảm đi theo con đường riêng.',
    asPersonalYear: 'Năm cá nhân số 1 là năm khởi đầu mới. Hãy gieo hạt cho những dự án mới, đặt mục tiêu táo bạo và tin vào trực giác của mình.',
  },
  2: {
    number: 2,
    nameVi: 'Số Hợp Tác',
    keywords: ['hợp tác', 'ngoại giao', 'nhạy cảm', 'hài hòa'],
    general: 'Số 2 đại diện cho sự hợp tác, ngoại giao và khả năng cảm thông. Bạn là người hòa giải bẩm sinh, giỏi lắng nghe và tạo sự hài hòa.',
    asLifePath: 'Con đường đời số 2 dẫn bạn đến vai trò người hòa giải và hợp tác. Bạn sinh ra để kết nối mọi người, tạo sự hài hòa và hỗ trợ người khác thành công.',
    asExpression: 'Bạn thể hiện bản thân qua sự tinh tế và khả năng ngoại giao. Tài năng của bạn nằm ở việc hợp tác, lắng nghe và tạo cầu nối giữa mọi người.',
    asSoulUrge: 'Tâm hồn bạn khao khát sự hòa bình, tình yêu và mối quan hệ sâu sắc. Bạn muốn được yêu thương, chia sẻ và sống trong môi trường hài hòa.',
    asPersonality: 'Bạn tạo ấn tượng nhẹ nhàng, dễ gần và đáng tin cậy. Người khác thấy bạn là người biết lắng nghe, thấu hiểu và luôn sẵn sàng giúp đỡ.',
    asBirthday: 'Sinh ngày mang năng lượng số 2 cho thấy bạn có khả năng ngoại giao tự nhiên, nhạy cảm với cảm xúc người khác và giỏi làm việc nhóm.',
    asMaturity: 'Khi trưởng thành, bạn sẽ phát triển sâu hơn khả năng hợp tác và ngoại giao. Nửa sau cuộc đời bạn tìm thấy ý nghĩa qua các mối quan hệ.',
    asChallenge: 'Thử thách số 2 yêu cầu bạn vượt qua sự nhút nhát, thiếu quyết đoán hoặc quá phụ thuộc vào người khác. Bạn cần học cách tự tin hơn.',
    asPinnacle: 'Đỉnh cao số 2 mang đến cơ hội phát triển qua hợp tác và các mối quan hệ. Đây là thời kỳ kiên nhẫn, ngoại giao và xây dựng nền tảng.',
    asPersonalYear: 'Năm cá nhân số 2 là năm kiên nhẫn và hợp tác. Hãy chú ý đến chi tiết, xây dựng mối quan hệ và chờ đợi thời cơ chín muồi.',
  },
  3: {
    number: 3,
    nameVi: 'Số Sáng Tạo',
    keywords: ['sáng tạo', 'giao tiếp', 'vui vẻ', 'nghệ thuật'],
    general: 'Số 3 tượng trưng cho sự sáng tạo, giao tiếp và niềm vui. Bạn có khả năng nghệ thuật bẩm sinh và luôn mang năng lượng tích cực.',
    asLifePath: 'Con đường đời số 3 dẫn bạn đến sự biểu đạt sáng tạo. Bạn sinh ra để truyền cảm hứng qua nghệ thuật, lời nói và khả năng sáng tạo không giới hạn.',
    asExpression: 'Bạn thể hiện bản thân qua sự sáng tạo và giao tiếp. Tài năng của bạn nằm ở khả năng diễn đạt, viết lách, nghệ thuật và truyền cảm hứng.',
    asSoulUrge: 'Tâm hồn bạn khao khát sự biểu đạt và sáng tạo. Bạn muốn được tỏa sáng, chia sẻ tầm nhìn nghệ thuật và mang niềm vui đến cho mọi người.',
    asPersonality: 'Bạn tạo ấn tượng vui vẻ, quyến rũ và đầy sức sống. Người khác bị thu hút bởi sự lạc quan, hài hước và phong cách độc đáo của bạn.',
    asBirthday: 'Sinh ngày mang năng lượng số 3 cho thấy bạn có tài giao tiếp, óc sáng tạo phong phú và khả năng truyền cảm hứng cho mọi người xung quanh.',
    asMaturity: 'Khi trưởng thành, bạn sẽ ngày càng tự do trong biểu đạt sáng tạo. Nửa sau cuộc đời là thời kỳ nghệ thuật và niềm vui sống nở rộ.',
    asChallenge: 'Thử thách số 3 yêu cầu bạn vượt qua sự phân tán, hời hợt hoặc thiếu tập trung. Bạn cần học cách kỷ luật để biến sáng tạo thành thành tựu.',
    asPinnacle: 'Đỉnh cao số 3 mang đến cơ hội tỏa sáng trong sáng tạo và giao tiếp. Đây là thời kỳ thuận lợi cho nghệ thuật, viết lách và các hoạt động xã hội.',
    asPersonalYear: 'Năm cá nhân số 3 là năm sáng tạo và giao tiếp. Hãy thể hiện bản thân, tham gia các hoạt động xã hội và theo đuổi đam mê nghệ thuật.',
  },
  4: {
    number: 4,
    nameVi: 'Số Ổn Định',
    keywords: ['ổn định', 'kỷ luật', 'chăm chỉ', 'nền tảng'],
    general: 'Số 4 đại diện cho sự ổn định, kỷ luật và xây dựng nền tảng vững chắc. Bạn là người đáng tin cậy, thực tế và kiên trì.',
    asLifePath: 'Con đường đời số 4 dẫn bạn đến sự xây dựng nền tảng vững chắc. Bạn sinh ra để tạo dựng hệ thống, tổ chức và mang lại sự ổn định cho cuộc sống.',
    asExpression: 'Bạn thể hiện bản thân qua sự chăm chỉ và kỷ luật. Tài năng của bạn nằm ở khả năng tổ chức, quản lý và xây dựng mọi thứ từ nền tảng.',
    asSoulUrge: 'Tâm hồn bạn khao khát sự an toàn, trật tự và ổn định. Bạn muốn xây dựng cuộc sống vững chắc cho bản thân và gia đình.',
    asPersonality: 'Bạn tạo ấn tượng đáng tin cậy, nghiêm túc và chuyên nghiệp. Người khác nhìn bạn như một người có trách nhiệm và đáng để tin tưởng.',
    asBirthday: 'Sinh ngày mang năng lượng số 4 cho thấy bạn có tính kỷ luật cao, khả năng tổ chức tốt và luôn hoàn thành công việc một cách có hệ thống.',
    asMaturity: 'Khi trưởng thành, bạn sẽ xây dựng được nền tảng vững chắc cho cuộc sống. Nửa sau cuộc đời là thời kỳ thu hoạch từ sự kiên trì và chăm chỉ.',
    asChallenge: 'Thử thách số 4 yêu cầu bạn vượt qua sự cứng nhắc, bảo thủ hoặc lười biếng. Bạn cần học cách linh hoạt hơn trong khi vẫn giữ kỷ luật.',
    asPinnacle: 'Đỉnh cao số 4 mang đến cơ hội xây dựng nền tảng lâu dài. Đây là thời kỳ làm việc chăm chỉ, kỷ luật và đầu tư cho tương lai.',
    asPersonalYear: 'Năm cá nhân số 4 là năm xây dựng nền tảng. Hãy làm việc chăm chỉ, tổ chức lại cuộc sống và đặt nền móng cho tương lai.',
  },
  5: {
    number: 5,
    nameVi: 'Số Tự Do',
    keywords: ['tự do', 'phiêu lưu', 'thay đổi', 'linh hoạt'],
    general: 'Số 5 tượng trưng cho sự tự do, phiêu lưu và thay đổi. Bạn yêu thích trải nghiệm mới, linh hoạt và không thích bị ràng buộc.',
    asLifePath: 'Con đường đời số 5 dẫn bạn đến sự tự do và phiêu lưu. Bạn sinh ra để trải nghiệm cuộc sống đa dạng, thích nghi với thay đổi và truyền cảm hứng tự do.',
    asExpression: 'Bạn thể hiện bản thân qua sự linh hoạt và đa tài. Tài năng của bạn nằm ở khả năng thích nghi, giao tiếp đa dạng và khám phá mọi khía cạnh cuộc sống.',
    asSoulUrge: 'Tâm hồn bạn khao khát tự do và trải nghiệm mới. Bạn muốn khám phá thế giới, không bị giới hạn và sống cuộc đời phong phú.',
    asPersonality: 'Bạn tạo ấn tượng năng động, phóng khoáng và đầy sức hút. Người khác thấy bạn là người thú vị, linh hoạt và luôn sẵn sàng cho điều mới.',
    asBirthday: 'Sinh ngày mang năng lượng số 5 cho thấy bạn có tinh thần phiêu lưu, khả năng thích nghi cao và luôn tìm kiếm sự đa dạng trong cuộc sống.',
    asMaturity: 'Khi trưởng thành, bạn sẽ tìm thấy sự tự do thực sự. Nửa sau cuộc đời là thời kỳ bạn dám sống theo cách riêng và khám phá những chân trời mới.',
    asChallenge: 'Thử thách số 5 yêu cầu bạn vượt qua sự bốc đồng, thiếu kiên nhẫn hoặc nghiện kích thích. Bạn cần học cách tự do có trách nhiệm.',
    asPinnacle: 'Đỉnh cao số 5 mang đến nhiều thay đổi và cơ hội mới. Đây là thời kỳ năng động, du lịch, mở rộng tầm nhìn và chấp nhận sự bất ngờ.',
    asPersonalYear: 'Năm cá nhân số 5 là năm thay đổi và tự do. Hãy sẵn sàng cho những bất ngờ, du lịch, và cởi mở với những trải nghiệm mới.',
  },
  6: {
    number: 6,
    nameVi: 'Số Trách Nhiệm',
    keywords: ['trách nhiệm', 'gia đình', 'chăm sóc', 'hài hòa'],
    general: 'Số 6 đại diện cho trách nhiệm, tình yêu gia đình và sự chăm sóc. Bạn là người yêu thương, có trách nhiệm và luôn quan tâm đến người khác.',
    asLifePath: 'Con đường đời số 6 dẫn bạn đến vai trò người chăm sóc và bảo vệ. Bạn sinh ra để yêu thương, phục vụ gia đình và cộng đồng, tạo sự hài hòa cho mọi người.',
    asExpression: 'Bạn thể hiện bản thân qua sự yêu thương và trách nhiệm. Tài năng của bạn nằm ở khả năng chăm sóc, tư vấn và tạo môi trường hài hòa.',
    asSoulUrge: 'Tâm hồn bạn khao khát tình yêu, gia đình hạnh phúc và sự hài hòa. Bạn muốn được yêu thương và chăm sóc những người thân yêu.',
    asPersonality: 'Bạn tạo ấn tượng ấm áp, đáng tin cậy và có trách nhiệm. Người khác thấy bạn là chỗ dựa vững chắc, luôn sẵn sàng giúp đỡ.',
    asBirthday: 'Sinh ngày mang năng lượng số 6 cho thấy bạn có tình yêu thương lớn, tinh thần trách nhiệm cao và khả năng chăm sóc người khác xuất sắc.',
    asMaturity: 'Khi trưởng thành, bạn sẽ tìm thấy niềm vui trong việc chăm sóc gia đình và cộng đồng. Nửa sau cuộc đời tập trung vào tình yêu và trách nhiệm.',
    asChallenge: 'Thử thách số 6 yêu cầu bạn vượt qua tính kiểm soát, hy sinh quá mức hoặc hoàn hảo chủ nghĩa. Bạn cần học cách yêu thương mà không ràng buộc.',
    asPinnacle: 'Đỉnh cao số 6 mang đến trách nhiệm gia đình và cộng đồng. Đây là thời kỳ yêu thương, phục vụ và xây dựng tổ ấm.',
    asPersonalYear: 'Năm cá nhân số 6 là năm gia đình và trách nhiệm. Hãy chăm sóc người thân, cải thiện không gian sống và đón nhận trách nhiệm mới.',
  },
  7: {
    number: 7,
    nameVi: 'Số Tâm Linh',
    keywords: ['tâm linh', 'trí tuệ', 'phân tích', 'nội tâm'],
    general: 'Số 7 tượng trưng cho sự tìm kiếm chân lý, trí tuệ và phát triển tâm linh. Bạn có khả năng phân tích sâu sắc và trực giác mạnh mẽ.',
    asLifePath: 'Con đường đời số 7 dẫn bạn đến sự tìm kiếm tri thức và chân lý. Bạn sinh ra để khám phá những bí ẩn của cuộc sống, phát triển trí tuệ và tâm linh.',
    asExpression: 'Bạn thể hiện bản thân qua sự phân tích và trí tuệ. Tài năng của bạn nằm ở khả năng nghiên cứu, quan sát sâu sắc và tìm kiếm sự thật.',
    asSoulUrge: 'Tâm hồn bạn khao khát sự hiểu biết sâu sắc và yên bình nội tâm. Bạn muốn tìm ra ý nghĩa cuộc sống và kết nối với thế giới tâm linh.',
    asPersonality: 'Bạn tạo ấn tượng bí ẩn, trí thức và đầy chiều sâu. Người khác thấy bạn là người sâu sắc, kín đáo và có phong thái thanh thoát.',
    asBirthday: 'Sinh ngày mang năng lượng số 7 cho thấy bạn có trí tuệ sắc bén, khả năng phân tích vượt trội và thiên hướng tâm linh mạnh mẽ.',
    asMaturity: 'Khi trưởng thành, bạn sẽ đi sâu hơn vào hành trình tâm linh và trí tuệ. Nửa sau cuộc đời là thời kỳ giác ngộ và bình an nội tâm.',
    asChallenge: 'Thử thách số 7 yêu cầu bạn vượt qua sự cô lập, hoài nghi quá mức hoặc xa rời thực tế. Bạn cần học cách cân bằng giữa nội tâm và thế giới bên ngoài.',
    asPinnacle: 'Đỉnh cao số 7 mang đến cơ hội phát triển tâm linh và trí tuệ. Đây là thời kỳ nghiên cứu, thiền định và khám phá chiều sâu cuộc sống.',
    asPersonalYear: 'Năm cá nhân số 7 là năm nội tâm và tìm kiếm. Hãy dành thời gian cho bản thân, nghiên cứu, thiền định và lắng nghe tiếng nói bên trong.',
  },
  8: {
    number: 8,
    nameVi: 'Số Quyền Lực',
    keywords: ['quyền lực', 'thành công', 'tài chính', 'tham vọng'],
    general: 'Số 8 đại diện cho quyền lực, thành công vật chất và khả năng quản lý. Bạn có tầm nhìn lớn, tham vọng và khả năng biến ước mơ thành hiện thực.',
    asLifePath: 'Con đường đời số 8 dẫn bạn đến thành công vật chất và quyền lực. Bạn sinh ra để quản lý tài chính, xây dựng sự nghiệp lớn và đạt được sự thịnh vượng.',
    asExpression: 'Bạn thể hiện bản thân qua sự thành đạt và quyền lực. Tài năng của bạn nằm ở khả năng quản lý, kinh doanh và tạo ra giá trị vật chất.',
    asSoulUrge: 'Tâm hồn bạn khao khát thành công, quyền lực và sự công nhận. Bạn muốn đạt được vị trí cao, tạo ảnh hưởng lớn và sống cuộc đời sung túc.',
    asPersonality: 'Bạn tạo ấn tượng quyền lực, thành đạt và chuyên nghiệp. Người khác nhìn bạn như người có khả năng, đáng tin cậy và biết cách kiếm tiền.',
    asBirthday: 'Sinh ngày mang năng lượng số 8 cho thấy bạn có tư duy kinh doanh, khả năng quản lý tài chính và tham vọng đạt thành tựu lớn.',
    asMaturity: 'Khi trưởng thành, bạn sẽ đạt đến đỉnh cao sự nghiệp và tài chính. Nửa sau cuộc đời là thời kỳ thu hoạch thành quả từ sự nỗ lực.',
    asChallenge: 'Thử thách số 8 yêu cầu bạn vượt qua lòng tham, tính kiểm soát hoặc coi trọng vật chất quá mức. Bạn cần học cách dùng quyền lực một cách khôn ngoan.',
    asPinnacle: 'Đỉnh cao số 8 mang đến thành công tài chính và sự công nhận. Đây là thời kỳ kinh doanh, đầu tư và đạt được vị trí xã hội cao.',
    asPersonalYear: 'Năm cá nhân số 8 là năm thu hoạch và thành tựu. Hãy tập trung vào tài chính, sự nghiệp và đón nhận phần thưởng xứng đáng.',
  },
  9: {
    number: 9,
    nameVi: 'Số Nhân Đạo',
    keywords: ['nhân đạo', 'từ bi', 'phụng sự', 'hoàn thành'],
    general: 'Số 9 tượng trưng cho lòng nhân ái, sự từ bi và phụng sự nhân loại. Bạn có tầm nhìn rộng lớn và mong muốn làm cho thế giới tốt đẹp hơn.',
    asLifePath: 'Con đường đời số 9 dẫn bạn đến sự phụng sự nhân loại. Bạn sinh ra để cống hiến, lan tỏa tình yêu thương và nâng cao ý thức cộng đồng.',
    asExpression: 'Bạn thể hiện bản thân qua lòng nhân ái và sự phụng sự. Tài năng của bạn nằm ở khả năng truyền cảm hứng, chữa lành và dẫn dắt bằng tình yêu.',
    asSoulUrge: 'Tâm hồn bạn khao khát phụng sự và mang lại giá trị cho cộng đồng. Bạn muốn sống một cuộc đời có ý nghĩa, giúp đỡ người khác và tạo di sản tốt đẹp.',
    asPersonality: 'Bạn tạo ấn tượng cao quý, rộng lượng và đầy lòng trắc ẩn. Người khác thấy bạn là người có tâm hồn đẹp, sẵn sàng giúp đỡ không tính toán.',
    asBirthday: 'Sinh ngày mang năng lượng số 9 cho thấy bạn có lòng nhân ái lớn, tầm nhìn rộng và khả năng thấu hiểu sâu sắc nỗi đau của người khác.',
    asMaturity: 'Khi trưởng thành, bạn sẽ tìm thấy sứ mệnh phụng sự lớn hơn. Nửa sau cuộc đời là thời kỳ bạn cống hiến tri thức và tình yêu cho nhân loại.',
    asChallenge: 'Thử thách số 9 yêu cầu bạn vượt qua sự ích kỷ, cảm xúc tiêu cực hoặc khó buông bỏ. Bạn cần học cách cho đi không điều kiện và chấp nhận kết thúc.',
    asPinnacle: 'Đỉnh cao số 9 mang đến cơ hội phụng sự nhân loại. Đây là thời kỳ hoàn thành, buông bỏ những gì không còn phù hợp và cống hiến cho cộng đồng.',
    asPersonalYear: 'Năm cá nhân số 9 là năm hoàn thành và buông bỏ. Hãy kết thúc những gì cần kết thúc, tha thứ, và chuẩn bị cho chu kỳ mới sắp bắt đầu.',
  },
  11: {
    number: 11,
    nameVi: 'Số Trực Giác Bậc Thầy',
    keywords: ['trực giác', 'tâm linh', 'truyền cảm hứng', 'nhạy cảm cao'],
    general: 'Số 11 là số bậc thầy đầu tiên, đại diện cho trực giác siêu phàm, tâm linh cao và khả năng truyền cảm hứng mạnh mẽ. Bạn là người mang thông điệp ánh sáng.',
    asLifePath: 'Con đường đời số 11 dẫn bạn đến sứ mệnh tâm linh cao cả. Bạn sinh ra để truyền cảm hứng, khai sáng và dẫn dắt bằng trực giác phi thường.',
    asExpression: 'Bạn thể hiện bản thân qua sự nhạy cảm cao và khả năng truyền cảm hứng. Tài năng của bạn nằm ở trực giác siêu phàm và khả năng kết nối tâm linh.',
    asSoulUrge: 'Tâm hồn bạn khao khát giác ngộ và sự kết nối tâm linh sâu sắc. Bạn muốn sống theo sứ mệnh cao cả và mang ánh sáng đến cho thế giới.',
    asPersonality: 'Bạn tạo ấn tượng bí ẩn, sâu sắc và có sức hút đặc biệt. Người khác cảm nhận được năng lượng tâm linh mạnh mẽ tỏa ra từ bạn.',
    asBirthday: 'Sinh ngày mang năng lượng số 11 cho thấy bạn có trực giác bẩm sinh vượt trội, khả năng ngoại cảm và sứ mệnh truyền cảm hứng cho người khác.',
    asMaturity: 'Khi trưởng thành, bạn sẽ hoàn toàn kích hoạt tiềm năng tâm linh. Nửa sau cuộc đời là thời kỳ bạn trở thành người hướng dẫn tâm linh cho người khác.',
    asChallenge: '',
    asPinnacle: 'Đỉnh cao số 11 mang đến sứ mệnh tâm linh lớn lao. Đây là thời kỳ trực giác đỉnh cao, truyền cảm hứng và khai sáng cho cộng đồng.',
    asPersonalYear: 'Năm cá nhân số 11 là năm tâm linh và truyền cảm hứng. Hãy tin vào trực giác, theo đuổi sứ mệnh cao cả và mở rộng nhận thức.',
  },
  22: {
    number: 22,
    nameVi: 'Số Kiến Trúc Sư Bậc Thầy',
    keywords: ['kiến trúc sư', 'tầm nhìn lớn', 'xây dựng', 'hiện thực hóa'],
    general: 'Số 22 là số bậc thầy mạnh mẽ nhất, đại diện cho khả năng biến tầm nhìn vĩ đại thành hiện thực. Bạn có tiềm năng xây dựng những công trình di sản cho nhân loại.',
    asLifePath: 'Con đường đời số 22 dẫn bạn đến sứ mệnh xây dựng vĩ đại. Bạn sinh ra để hiện thực hóa tầm nhìn lớn, tạo ra những thay đổi có ảnh hưởng toàn cầu.',
    asExpression: 'Bạn thể hiện bản thân qua khả năng xây dựng quy mô lớn. Tài năng của bạn nằm ở việc kết hợp tầm nhìn tâm linh với khả năng thực thi phi thường.',
    asSoulUrge: 'Tâm hồn bạn khao khát xây dựng di sản lâu dài cho nhân loại. Bạn muốn tạo ra những hệ thống, tổ chức và công trình vĩ đại có ảnh hưởng lớn.',
    asPersonality: 'Bạn tạo ấn tượng quyền lực, tầm nhìn xa và đáng kính. Người khác nhìn bạn như một kiến trúc sư bậc thầy có khả năng biến mọi ước mơ thành sự thật.',
    asBirthday: 'Sinh ngày mang năng lượng số 22 cho thấy bạn có tầm nhìn vĩ đại, khả năng xây dựng hệ thống và tiềm năng tạo ảnh hưởng toàn cầu.',
    asMaturity: 'Khi trưởng thành, bạn sẽ hiện thực hóa tầm nhìn vĩ đại nhất. Nửa sau cuộc đời là thời kỳ bạn xây dựng di sản có ý nghĩa cho nhiều thế hệ.',
    asChallenge: '',
    asPinnacle: 'Đỉnh cao số 22 mang đến cơ hội xây dựng di sản vĩ đại. Đây là thời kỳ bạn có thể tạo ra những thay đổi có ảnh hưởng sâu rộng đến nhân loại.',
    asPersonalYear: 'Năm cá nhân số 22 là năm xây dựng tầm nhìn lớn. Hãy dám nghĩ lớn, lập kế hoạch chi tiết và bắt tay xây dựng di sản của bạn.',
  },
  33: {
    number: 33,
    nameVi: 'Số Thầy Giáo Bậc Thầy',
    keywords: ['thầy giáo', 'tình yêu vô điều kiện', 'chữa lành', 'phụng sự'],
    general: 'Số 33 là số bậc thầy cao nhất, đại diện cho tình yêu vô điều kiện, khả năng chữa lành và phụng sự. Bạn là người thầy tâm linh, nâng đỡ và giác ngộ cho nhân loại.',
    asLifePath: 'Con đường đời số 33 dẫn bạn đến sứ mệnh chữa lành và dạy dỗ nhân loại. Bạn sinh ra để yêu thương vô điều kiện và nâng cao nhận thức cho cộng đồng.',
    asExpression: 'Bạn thể hiện bản thân qua tình yêu vô điều kiện và sự phụng sự. Tài năng của bạn nằm ở khả năng chữa lành, dạy dỗ và truyền bá tình yêu thương.',
    asSoulUrge: 'Tâm hồn bạn khao khát yêu thương và phụng sự ở mức cao nhất. Bạn muốn trở thành người thầy, người chữa lành và người truyền bá ánh sáng.',
    asPersonality: 'Bạn tạo ấn tượng ấm áp, thánh thiện và đầy tình yêu thương. Người khác cảm nhận được năng lượng chữa lành và bình an tỏa ra từ bạn.',
    asBirthday: 'Sinh ngày mang năng lượng số 33 cho thấy bạn có tình yêu thương vô bờ, khả năng chữa lành tâm hồn và sứ mệnh nâng đỡ nhân loại.',
    asMaturity: 'Khi trưởng thành, bạn sẽ đạt đến trạng thái tình yêu vô điều kiện. Nửa sau cuộc đời là thời kỳ bạn trở thành người thầy chữa lành cho thế giới.',
    asChallenge: '',
    asPinnacle: 'Đỉnh cao số 33 mang đến sứ mệnh chữa lành nhân loại. Đây là thời kỳ tình yêu vô điều kiện và phụng sự cao cả nhất.',
    asPersonalYear: 'Năm cá nhân số 33 là năm phụng sự và tình yêu vô điều kiện. Hãy cho đi không tính toán và trở thành ánh sáng cho cộng đồng.',
  },
}
